# Generated by Django 2.2.7 on 2019-12-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
