# Generated by Django 2.2.7 on 2019-12-19 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lancamento', '0005_auto_20191217_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='tipolancamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipolancamento_fk', to='lancamento.TipoLancamento'),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receita_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
