# Generated by Django 2.2.7 on 2020-01-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento', '0007_auto_20191219_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='tipolancamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipolancamento_fk', to='lancamento.TipoLancamento'),
        ),
        migrations.CreateModel(
            name='LancamentoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itenslancamento', to='lancamento.Lancamento')),
            ],
        ),
    ]
