# Generated by Django 2.2.7 on 2020-01-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento', '0009_auto_20200108_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='tipolancamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipolancamento_fk', to='lancamento.TipoLancamento'),
        ),
        migrations.AlterField(
            model_name='lancamentoitem',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itenslancamento', to='lancamento.Lancamento'),
        ),
    ]
