# Generated by Django 2.2.7 on 2020-01-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromovimento',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
